services:
  kavita:
    #image: lscr.io/linuxserver/kavita:latest
    image: lscr.io/linuxserver/kavita:8.3
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/atort88/docker/kavita/config:/config
      - /media/comics_nas/Comics/kavita_comic_db:/comics
    ports:
      - "192.168.0.208:5050:5000"
    restart: unless-stopped
